language: node_js

node_js:
  - 14

notifications:
  email: false

branches:
  only:
    - main

script:
  - echo "deploying"

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP
  on:
    branch: main
