language: node_js

node_js:
  - 12

notifications:
  email: false

branches:
  only:
    - main

script:
  - echo "deploying"

deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP
  on:
    branch: main
